- name: lab4
  hosts: all
  become: true

  #gather_facts: false
  # roles:
  # - roles/lean_delivery_slave
  tasks:
  - name: Update APT package manager repositories cache
    apt:
      update_cache: yes
      force_apt_get: yes 
      cache_valid_time: 3600

  - name: Install OpenJDK Java
    become: yes
    apt:
      name: openjdk-8-jdk
      state: present
     
  - name: Add signing key
    ansible.builtin.apt_key:
      url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
      state: present
  - name: Add repository into sources list
    ansible.builtin.apt_repository:
      repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present
      filename: docke
  - name: Install Docker
    ansible.builtin.apt:
      name:
        - docker
        - docker.io
        - docker-compose
        - docker-registry
      state: latest
      update_cache: true

  - name: Ensure docker deamon is running
    service:
      name: docker
      state: started
    become: true

  - name: Ensure My docker container is running
    docker_container:
      name: testing
      image: busybox
      state: started
    become: true

  - name: Update repository
    apt_repository:
      repo: 'ppa:git-core/ppa'
      state: present

  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes

  - name: Ansible file module create home directory    
    file:
      path: ~/jenkins_home    
      state: directory
  
  - name: Ansible file module create bin directory    
    file:
      path: ~/bin    
      state: directory
  